### ISSUE TITLE
ENANCHMENT - Add ability to empty the list of symfony and rescan folders

### ISSUE THREAD

**Issue by lorenzo-pezzali** [raniel86/startsymfonies#1]
Add the ability to empty the list of the symfonies and rescan the folders for searching symfonies.

This is needed because if i bulk delete symfonies folder from the cli i have to remove singolarly from the list.

* UPDATE
I've seen that there is a command for doing that, i think a function from web interface is also useful

**Comment by dsabre** [comment]
Resolved.
